### ISSUE TITLE
Adding .NET development project

### ISSUE THREAD

**Issue by dariogriffo** [tronprotocol/wiki#123]
I have started working a .NET version of the protocol. Adding all the grpc calls and first version of address generation and transaction signing.
The code can be accessed here
https://github.com/griffo-io/tron.net
I would like also this to participate in the Tron's incentive program. 
What are the required steps for this?

**Comment by kookiekrak** [comment]
@dariogriffo hey can you email me at tian@Tron.network? I'll invite you to the discord group. Also we can discuss your dotnet tron integration!
