### ISSUE TITLE
Node.js Pls....

### ISSUE THREAD

**Issue by JSRenaissance** [tronprotocol/wiki#3]
Could it work in Node.js?

**Comment by sasaxie** [comment]
No.

**Comment by JSRenaissance** [comment]
Curious why no? How about on electron (io) through WebGL GPU?

**Comment by sasaxie** [comment]
Not currently.

**Comment by JSRenaissance** [comment]
Got it, thx @sasaxie ... I want to put games in tron. 👍

**Comment by sasaxie** [comment]
Hope soon~:grin:

**Comment by ruchern** [comment]
Please direct this question to the https://github.com/tronprotocol/java-tron repository.
