### ISSUE TITLE
Glitch? Tron Wallet two addresses

### ISSUE THREAD

**Issue by herosdroid** [tronprotocol/wiki#4]
@sasaxie 

Hi Tron Team - I've found a glitch perhaps? 

When I create a wallet at debug.tronlab.com vs. www.tronlab.com they are giving me two different tron deposit wallet addresses (someone linked me to the debug site first). Tron.network gave me the same deposit address as www.tronlab.com. The only deposit address that is NOT the same is debug.tronlab.com.  

So I created account, did a deposit (to debug.tronlab.com) and the deposit is NOT showing in the account. Is the debug website not functioning properly to recognize the deposit? Who can I contact to resolve issue? I couldn't find any Tron team members to email. 

Thanks

**Comment by silvertipp** [comment]
Debug is most likely a test url. I'm not sure why you would expect that to be the proper address.

**Comment by herosdroid** [comment]
Someone had sent that to me and I wasn't paying attention. I suspect that as well hence the reason it's not showing. I just need someone who can assist in getting those funds into a wallet that is accessible.

**Comment by sasaxie** [comment]
Got it~

**Comment by sasaxie** [comment]
debug.tronlab.com is test env. It's okay.

**Comment by ruchern** [comment]
This is the Wiki page. This question should be directed to the https://github.com/tronprotocol/java-tron/ repository.
