### ISSUE TITLE
Plan to maintain a full fledge wiki instead of markdown documentation

### ISSUE THREAD

**Issue by ruchern** [tronprotocol/wiki#5]
Continued from https://github.com/tronprotocol/java-tron/issues/22

**Comment by styk-tv** [comment]
@sasaxie please create tronprotocol account at https://readthedocs.org/ and I will wire this up with a PR in /docs folder on this wiki repo.

**Comment by sasaxie** [comment]
@styk-tv done

**Comment by ruchern** [comment]
@sasaxie awesome, I am looking forward to start contributing this weekend!

**Comment by sasaxie** [comment]
@ruchern thanks

**Comment by tronfoundation** [comment]
@styk-tv https://github.com/tronprotocol/wiki/invitations

**Comment by ruchern** [comment]
@tronfoundation I cannot see the link

**Comment by sasaxie** [comment]
@ruchern https://github.com/tronprotocol/wiki/invitations

**Comment by ruchern** [comment]
@sasaxie got it now. Thanks!

**Comment by styk-tv** [comment]
@sasaxie @ruchern I still need ReadTheDocs maintainer access for user 'polfilm' in order to configure build/publish properly if you want me to set this up today. I'm preparing push into wiki with first version in the mean time.

**Comment by styk-tv** [comment]
as soon as first version is there we should workout internationalisation scheme so its built from zero with this in mind. otherwise this will be a painful exercise later. this will also immediately open avenue for others to contribute language drops. look here: http://www.sphinx-doc.org/en/stable/intl.html#update-your-po-files-by-new-pot-files  

for now i'm still waiting for maintainer access to RTD. ping > @tronfoundation @sasaxie

**Comment by sasaxie** [comment]
@styk-tv done

**Comment by styk-tv** [comment]
no one should ever have permissions to push to master. workflow is as follows. you create branch or fork, to come back create pr against master, we will set up travis-ci to verify syntax, once the syntax is correct we will allow merge, as soon as merge is done readthedocs will publish live. later we can establish more advanced workflows and multilanguage etc.  i can contribute some time to set this up.

first version is is live (from branch 'issue--5-readthedocs') and it doesn't have images but I'm sure you can take it from here @ruchern 

http://tron-wiki.readthedocs.io/introduction.html

anything else should be filed as new issue. i'm closing this.

**Comment by ruchern** [comment]
What I meant was collaborators doesn’t seemed to have the permission to merge PR into masters too. Have to be part of the organisation to do that.

**Comment by sasaxie** [comment]
@ruchern The master branch is protected and only the administrator can commit PR into the master branch.
