### ISSUE TITLE
CNAME

### ISSUE THREAD

**Issue by styk-tv** [tronprotocol/wiki#8]
wiki.tron.network (or other agreed domain) add CNAME record pointing to `readthedocs.io.`

**Comment by styk-tv** [comment]
matching domain has to be added to RTD/Admin/Domains for a match

**Comment by sasaxie** [comment]
Got it~

**Comment by sasaxie** [comment]
@styk-tv Done.http://wiki.tron.network/

**Comment by ruchern** [comment]
Awesome work!

**Comment by styk-tv** [comment]
Totally cool :) Closing.
